name: Desplegar Projecte

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Configurar Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '20'

      - name: Instal·lar dependències
        run: npm install

      - name: Build projecte
        run: npm run build
